
["server and client"]
	#use if respect_difficulty is false! 'rare, common, often'
	spawn_rate = "common"
	#if true, it will adjust the rareness of the Knocker to the ingame difficulty
	respect_difficulty = true

